### login
POST http://118.24.195.108:7001/api/v1/user/login HTTP/1.1
content-type: application/json

{
    "username": "tlgc",
    "password": "qwer1234"
}

### get weixin user
GET http://118.24.195.108:7001/api/v1/wuser HTTP/1.1
User-Agent: rest-client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJ0bGdjIiwiaWF0IjoxNTUxOTQ0OTE0LCJleHAiOjE1NTIxMTc3MTR9.xTBjhzOtz1cbSr848Qvi0JGRKUAfKDHuHTHMgOe6WRs
content-type: application/json

### get system log
GET http://118.24.195.108:7001/api/v1/log HTTP/1.1
User-Agent: rest-client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJ0bGdjIiwiaWF0IjoxNTUxOTQ0OTE0LCJleHAiOjE1NTIxMTc3MTR9.xTBjhzOtz1cbSr848Qvi0JGRKUAfKDHuHTHMgOe6WRs
content-type: application/json